package com.classapp

import android.app.*
import android.content.*
import android.os.Bundle
import android.view.Gravity
import android.view.View
import android.widget.*
import androidx.appcompat.app.AppCompatActivity
import androidx.lifecycle.lifecycleScope
import com.classapp.data.AppDatabase
import com.classapp.model.*
import com.classapp.util.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

class MainActivity:AppCompatActivity(){
 private lateinit var db:AppDatabase; private lateinit var root:LinearLayout
 private fun base(title:String){root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(24,24,24,24);layoutDirection=View.LAYOUT_DIRECTION_RTL};setContentView(ScrollView(this).apply{addView(root)});root.addView(TextView(this).apply{text=title;textSize=24f;setPadding(4,4,4,20);gravity=Gravity.RIGHT})}
 private fun button(t:String,a:()->Unit)=Button(this).apply{text=t;setOnClickListener{a()}}
 private fun edit(h:String)=EditText(this).apply{hint=h;setPadding(12,12,12,12)}
 override fun onCreate(b:Bundle?){super.onCreate(b);db=AppDatabase.get(this);home()}
 private fun home(){base("سیستم مدیریت آموزشگاه — کلاس V3");root.addView(TextView(this).apply{text="نسخه ۳: پایگاه‌داده دائمی، گزارش واقعی، ورود Excel بدون Apache POI و پشتیبان‌گیری";textSize=16f;setPadding(4,4,4,18)});root.addView(button("👨‍🎓 زبان‌آموزان"){students()});root.addView(button("👨‍🏫 اساتید"){teachers()});root.addView(button("📚 دوره‌ها"){courses()});root.addView(button("🏫 کلاس‌ها"){classes()});root.addView(button("📝 گزارش روزانه"){daily()});root.addView(button("📊 گزارش هفتگی"){report(7,"گزارش هفتگی")});root.addView(button("📅 گزارش ماهانه"){report(30,"گزارش ماهانه")});root.addView(button("💾 پشتیبان‌گیری JSON"){backup()});root.addView(button("ℹ️ معماری V3"){about()})}
 private fun back(){home()}
 private fun students(){base("زبان‌آموزان");val search=edit("جستجو: کد، نام، نام خانوادگی، موبایل، کد ملی");root.addView(search);root.addView(button("➕ ثبت زبان‌آموز"){studentForm()});root.addView(button("📥 ورود Excel"){pick(100)});val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};root.addView(list);fun load(){lifecycleScope.launch{val q="%${search.text}%";val xs=withContext(Dispatchers.IO){if(search.text.isBlank())db.students().all() else db.students().search(q)};list.removeAllViews();xs.forEach{x->list.addView(TextView(this@MainActivity).apply{text="${x.code} — ${x.firstName} ${x.lastName}\n${x.mobile} | کد ملی: ${x.nationalId}";textSize=17f;setPadding(10,14,10,14)})}}};search.setOnEditorActionListener{_,_,_->load();true};load();root.addView(button("بازگشت"){back()})}
 private fun studentForm(){base("ثبت زبان‌آموز");val e=(0..5).map{edit(listOf("نام","نام خانوادگی","موبایل","کد ملی","تاریخ تولد","توضیحات")[it])};e.forEach{root.addView(it)};root.addView(button("ذخیره"){val first=e[0].text.toString().trim();val last=e[1].text.toString().trim();if(first.isBlank()||last.isBlank()){Toast.makeText(this,"نام و نام خانوادگی الزامی است",Toast.LENGTH_LONG).show();return@button};lifecycleScope.launch(Dispatchers.IO){db.students().upsert(Student(Id.id(),Id.studentCode(),first,last,e[2].text.toString(),e[3].text.toString(),e[4].text.toString(),e[5].text.toString()));withContext(Dispatchers.Main){students()}}});root.addView(button("لغو"){students()})}
 private fun teachers(){base("اساتید");root.addView(button("➕ ثبت مدرس"){teacherForm()});val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};root.addView(list);lifecycleScope.launch{db.teachers().all().forEach{x->list.addView(TextView(this@MainActivity).apply{text="${x.code} — ${x.name}\n${x.mobile}";setPadding(10,14,10,14);textSize=17f})}};root.addView(button("بازگشت"){back()})}
 private fun teacherForm(){base("ثبت مدرس");val n=edit("نام و نام خانوادگی");val m=edit("موبایل");val note=edit("توضیحات");listOf(n,m,note).forEach{root.addView(it)};root.addView(button("ذخیره"){if(n.text.isBlank())return@button;lifecycleScope.launch(Dispatchers.IO){db.teachers().upsert(Teacher(Id.id(),Id.teacherCode(),n.text.toString(),m.text.toString(),note.text.toString()));withContext(Dispatchers.Main){teachers()}}});root.addView(button("لغو"){teachers()})}
 private fun courses(){base("دوره‌ها");root.addView(button("➕ ثبت دوره"){courseForm()});val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};root.addView(list);lifecycleScope.launch{db.courses().all().forEach{x->list.addView(TextView(this@MainActivity).apply{text="${x.code} — ${x.name}\nسطح: ${x.level} | شهریه: ${x.tuition}";setPadding(10,14,10,14);textSize=17f})}};root.addView(button("بازگشت"){back()})}
 private fun courseForm(){base("ثبت دوره");val n=edit("نام دوره");val l=edit("سطح");val t=edit("شهریه");val note=edit("توضیحات");listOf(n,l,t,note).forEach{root.addView(it)};root.addView(button("ذخیره"){if(n.text.isBlank())return@button;lifecycleScope.launch(Dispatchers.IO){db.courses().upsert(Course(Id.id(),Id.courseCode(),n.text.toString(),l.text.toString(),t.text.toString().toLongOrNull()?:0,note.text.toString()));withContext(Dispatchers.Main){courses()}}});root.addView(button("لغو"){courses()})}
 private fun classes(){base("کلاس‌ها");root.addView(button("➕ ثبت کلاس"){classForm()});root.addView(button("📥 ورود Excel"){pick(101)});val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};root.addView(list);lifecycleScope.launch{val cs=db.classes().all();val courses=db.courses().all().associateBy{it.id};val teachers=db.teachers().all().associateBy{it.id};cs.forEach{x->list.addView(TextView(this@MainActivity).apply{text="${x.code} — ${x.name}\n${courses[x.courseId]?.name?: "بدون دوره"} | ${teachers[x.teacherId]?.name?: "بدون مدرس"}\n${x.startDate} تا ${x.endDate} | ${x.days} | ${x.time}";setPadding(10,14,10,14);textSize=17f})})};root.addView(button("بازگشت"){back()})}
 private fun classForm(){base("ثبت کلاس");val n=edit("نام کلاس");val sd=edit("تاریخ شروع yyyy/MM/dd");val ed=edit("تاریخ پایان yyyy/MM/dd");val days=edit("روزهای برگزاری");val time=edit("ساعت");val cap=edit("ظرفیت");val note=edit("توضیحات");listOf(n,sd,ed,days,time,cap,note).forEach{root.addView(it)};lifecycleScope.launch{val cs=db.courses().all();val ts=db.teachers().all();val sp=Spinner(this@MainActivity);sp.adapter=ArrayAdapter(this@MainActivity,android.R.layout.simple_spinner_dropdown_item,cs.map{it.name});root.addView(sp,0);val tp=Spinner(this@MainActivity);tp.adapter=ArrayAdapter(this@MainActivity,android.R.layout.simple_spinner_dropdown_item,ts.map{it.name});root.addView(tp,0);root.addView(button("ذخیره"){val ci=sp.selectedItemPosition;val ti=tp.selectedItemPosition;if(n.text.isBlank()||cs.isEmpty())return@button;lifecycleScope.launch(Dispatchers.IO){db.classes().upsert(SchoolClass(Id.id(),Id.classCode(),n.text.toString(),cs[ci].id,if(ts.isEmpty())"" else ts[ti].id,sd.text.toString(),ed.text.toString(),days.text.toString(),time.text.toString(),cap.text.toString().toIntOrNull()?:0,note.text.toString()));withContext(Dispatchers.Main){classes()}}})};root.addView(button("لغو"){classes()})}
 private fun daily(){base("گزارش روزانه");val date=edit("تاریخ yyyy/MM/dd");val cls=edit("کد کلاس");val teacher=edit("کد مدرس");val txt=edit("متن کامل گزارش روزانه").apply{minLines=8;gravity=Gravity.TOP};listOf(date,cls,teacher,txt).forEach{root.addView(it)};root.addView(button("ذخیره گزارش"){if(date.text.isBlank()||txt.text.isBlank())return@button;lifecycleScope.launch(Dispatchers.IO){db.dailyReports().upsert(DailyReport(Id.id(),cls.text.toString(),date.text.toString(),teacher.text.toString(),txt.text.toString()));withContext(Dispatchers.Main){Toast.makeText(this@MainActivity,"گزارش ذخیره شد",Toast.LENGTH_SHORT).show();daily()}}});root.addView(button("بازگشت"){back()})}
 private fun report(days:Int,title:String){base(title);val from=edit("از تاریخ yyyy/MM/dd");val to=edit("تا تاریخ yyyy/MM/dd");root.addView(from);root.addView(to);val list=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};root.addView(list);root.addView(button("نمایش گزارش"){lifecycleScope.launch{val a=withContext(Dispatchers.IO){db.dailyReports().between(from.text.toString(),to.text.toString())};list.removeAllViews();a.forEach{x->list.addView(TextView(this@MainActivity).apply{text="${x.date} | کلاس ${x.classId}\n${x.text}";textSize=16f;setPadding(10,14,10,14)})}}});root.addView(button("بازگشت"){back()})}
 private fun backup(){lifecycleScope.launch{val intent=Intent(Intent.ACTION_CREATE_DOCUMENT).apply{type="application/json";putExtra(Intent.EXTRA_TITLE,"class_v3_backup.json")};startActivityForResult(intent,900)}}
 private fun about(){base("معماری V3");root.addView(TextView(this).apply{text="پایگاه داده Room و SQLite\nشناسه‌های یکتا\nورود XLSX بدون Apache POI\nگزارش روزانه با تاریخ واقعی\nگزارش هفتگی/ماهانه با فیلتر بازه\nماژول‌های پایه مدرس، دوره و کلاس\nآماده توسعه ثبت‌نام، حضور و غیاب، شهریه، پرداخت، نمرات و کارنامه\nپشتیبان‌گیری JSON\nminSdk 26 / targetSdk 35 / Java 17\n\nنکته: برای Build قابل تکرار، Gradle Wrapper نیز در بسته نهایی قرار می‌گیرد.";textSize=17f;setPadding(8,8,8,20)});root.addView(button("بازگشت"){back()})}
 private fun pick(code:Int){startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";addCategory(Intent.CATEGORY_OPENABLE)},code)}
 override fun onActivityResult(req:Int,res:Int,data:Intent?){super.onActivityResult(req,res,data);if(res!=RESULT_OK||data?.data==null)return;if(req==900){lifecycleScope.launch(Dispatchers.IO){contentResolver.openOutputStream(data.data!!)?.use{Backup.export(db,it)}};Toast.makeText(this,"پشتیبان ذخیره شد",Toast.LENGTH_LONG).show();return};lifecycleScope.launch{try{val rows=withContext(Dispatchers.IO){contentResolver.openInputStream(data.data!!)?.use{XlsxReader.read(it)}?:emptyList()};withContext(Dispatchers.IO){if(req==100){rows.drop(1).forEach{r->if(r.getOrNull(0).orEmpty().isNotBlank())db.students().upsert(Student(Id.id(),r.getOrNull(0).orEmpty().ifBlank{Id.studentCode()},r.getOrNull(1).orEmpty(),r.getOrNull(2).orEmpty(),r.getOrNull(3).orEmpty(),r.getOrNull(4).orEmpty(),r.getOrNull(5).orEmpty(),r.getOrNull(6).orEmpty()))}}else{rows.drop(1).forEach{r->if(r.getOrNull(1).orEmpty().isNotBlank())db.classes().upsert(SchoolClass(Id.id(),r.getOrNull(0).orEmpty().ifBlank{Id.classCode()},r.getOrNull(1).orEmpty(),r.getOrNull(2).orEmpty(),r.getOrNull(3).orEmpty(),r.getOrNull(4).orEmpty(),r.getOrNull(5).orEmpty(),r.getOrNull(6).orEmpty(),r.getOrNull(7).orEmpty(),0,r.getOrNull(8).orEmpty()))}}};withContext(Dispatchers.Main){Toast.makeText(this@MainActivity,"ورود Excel انجام شد",Toast.LENGTH_LONG).show();if(req==100)students() else classes()}}catch(e:Exception){Toast.makeText(this@MainActivity,"خطا در Excel: ${e.message}",Toast.LENGTH_LONG).show()}}}
}
